### ISSUE TITLE
LaTeX advice on figure placement is incorrect

### ISSUE THREAD

**Issue by ringprince** [rstudio/rmarkdown-cookbook#379]
According to the authorities on [stackexchange](https://tex.stackexchange.com/questions/652253/howto-use-figure-placement-h-in-scrartcl) the advice on how to make figures appear in place in the LaTeX export (as given in [6.5.2 Prevent figures from floating](https://bookdown.org/yihui/rmarkdown-cookbook/figure-placement.html#prevent-figures-from-floating)) needs to be corrected.

It should be changed from

```
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
```

to

```
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

(Note the removed `!`).

**Comment by cderv** [comment]
Thank you
