### ISSUE TITLE
v_spaces is not recognized anymore.

### ISSUE THREAD

**Issue by piiskop** [rstudio/rmarkdown-cookbook#386]
i used to use the method for displaying line numbers using the instructions in [Add line numbers to source code](https://bookdown.org/yihui/rmarkdown-cookbook/hook-number.html) however, after upgrading all the packages, it does not work anymore as `v_spaces` is not recognized anymore.

**Comment by yihui** [comment]
The internal function `v_spaces()` has been removed from **knitr**. I just updated the book to use `strrep()` in base R instead. Sorry about the confusion!
