### ISSUE TITLE
May I ask how to add the original latex code

### ISSUE THREAD

**Issue by zoushucai** [rstudio/rmarkdown-cookbook#388]
For example, sometimes I want to directly insert raw latex code into the `rmd` file to generate a PDF, but I don't know how to do it?
Not to display the latex code, but to compile and output the raw latex code

**Comment by cderv** [comment]
This is explain in the book already 
https://bookdown.org/yihui/rmarkdown-cookbook/raw-latex.html

I believe this is what you are looking for. Please reopen if not

**Comment by zoushucai** [comment]
> believe this is what you are looking for. Please reopen if not

Thank you. I know this, but later I realized that it turned out to be an issue with the visual mode of Rstduio

**Comment by cderv** [comment]
> later I realized that it turned out to be an issue with the visual mode of Rstudio

For this issue you can open in the rstudio IDE repo then. Thanks !
